// Code generated by logcopter-gen; DO NOT EDIT.

package list

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.docmgr.cmd.docmgr.cmds.list")
