- type: local
  path: /home/manuel/.cursor/projects/home-manuel-workspaces-2025-12-11-improve-yaml-frontmatter-handling-docmgr-docmgr/agent-tools/03b2ac14-e8a7-4f45-8d0c-06bcbc6f5481.txt
  lastFetched: 2025-12-13T16:15:22.087248345-05:00
