- type: local
  path: /home/manuel/workspaces/2025-11-04/code-review-kball-pr/glazed/pkg/doc/tutorials/05-build-first-command.md
  lastFetched: 2025-11-04T17:50:28.904871891-05:00
- type: local
  path: /home/manuel/workspaces/2025-11-04/code-review-kball-pr/glazed/pkg/doc/topics/how-to-write-good-documentation-pages.md
  lastFetched: 2025-11-04T17:50:28.943771933-05:00
