// Code generated by logcopter-gen; DO NOT EDIT.

package docmgrctx

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.docmgr.pkg.diagnostics.docmgrctx")
